### ISSUE TITLE
Wykład 3 zadanie 4

### ISSUE THREAD

**Issue by sBwin1** [daftcode/daftacademy-python_levelup-spring2019#12]
Może ktoś wie, bo wyskakuje mi taki błąd, a wydaje mi się, że ten błąd wynika z błędu w testach. 

More info
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 26, in test_hello
    dom = htmldom.HtmlDom().createDom(r1.text)
NameError: name 'htmldom' is not defined

Dodam, że na mojej przeglądarce uzyskuje wynik działania aplikacji taki jaki powinien wynikać z treści zadania.

**Comment by RafalKornel** [comment]
Mam ten sam problem, moja aplikacja zwraca z endpointu /hello ładnego htmla, jednak ten nie przechodzi testów

**Comment by RafalKornel** [comment]
Teraz błąd się zmienił, wygląda tak:

> Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 33, in test_hello
    self.assertTrue(s1)
AssertionError: None is not true

Jest to test 'hello'.
Aplikacja zwraca taką html'ke (github ucina \<html\> i \</html\>):

> <html>
	<body>
		<p id=greeting>Hello, {{ user }}!</p>
	</body>
</html>


Tak wygląda kod odpowiedzialny za ten endpoint:

> @app.route('/hello')
@auth_needed
def hello():
    render = render_template('hello.html', user = user)
    return render

**Comment by sBwin1** [comment]
Teraz to i ja mam taki sam błąd. Może komuś się udało przejść testy i zasugeruje, gdzie błąd :)?

**Comment by sBwin1** [comment]
Daj id="greeting" to przejdzie testy :)

**Comment by RafalKornel** [comment]
Faktycznie ruszyło, dzięki!
