### ISSUE TITLE
3.3

### ISSUE THREAD

**Issue by przemko0** [daftcode/daftacademy-python_levelup-spring2019#13]
Przy wykonywaniu testu wyskakuje następujący błąd
`Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 23, in test_test_logout
    cookies = r1.history[-1].cookies
IndexError: list index out of range`
mimo, że wydaje mi się, że aplikacja działa poprawnie. Coś nie tak z testem, czy jednak to moja wina?

**Comment by mateusz94** [comment]
Cześć,
zdaje się, że nie wykonujesz przekierowania po poprawnym zalogowaniu.
@irqize: podeślij proszę link do repozytorium z kodem.

**Comment by konradorlinski** [comment]
Mam tego typu błąd:
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 28, in test_test_logout
    self.assertEqual(r2.url, self.URL_ROOT)
AssertionError: 'http://daftcode-spring-lvlup-konrad-1.herokuapp.com/logout' != 'http://daftcode-spring-lvlup-konrad-1.herokuapp.com/'
- http://daftcode-spring-lvlup-konrad-1.herokuapp.com/logout
?                                                     ------
+ http://daftcode-spring-lvlup-konrad-1.herokuapp.com/
```
A przekierowanie po wylogowaniu mam tak zrobione:
```
    if 'logged' in session:
        session.pop('logged', None)
        return redirect('/', code=200)
    else:
        return redirect("/login", code=200)
```
Co może być nie tak?

**Comment by moty-daft** [comment]
Ten kawałek kodu wygląda sensownie wg mnie. Błąd wskazuje chyba na to, że nie przekierowuje ani na '/' ani na '/login', więc moje przypuszczenie byłoby takie, że może nie obsługujesz POST w '/logout'? Czy to działa Ci lokalnie (czy widzisz w konsoli przekierowanie)?

**Comment by konradorlinski** [comment]
Na localu działa przekierowanie bez problemu. A przy testach na heroku jest problem. Próbuje jeszcze ręcznie wytwstoeac na heroku, bo w sumie chyba tego nie robiłem.

**Comment by dbadocha** [comment]
Miałem podobny problem kiedy przy redirect podawałem status code inny niż 301

**Comment by gignacy** [comment]
U mnie też jest problem:

```
@app.route('/logout', methods=['POST'])
def logout():
    if 'user' in session:
        session.pop('user', None)
        return redirect('/', code=301)

    return redirect(url_for('login'), code=301)
```

error:

```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 33, in test_test_logout
    self.assertEqual(r3.status_code, 401)
AssertionError: 405 != 401
```

Wie ktoś może o co chodzi?

**Comment by moty-daft** [comment]
405 mówi o tym, że na danej ścieżce nie obsługujesz wybranej metody. Prawdopodobnie chodzi o brak GET na ścieżce /login.

**Comment by gignacy** [comment]
Dzięki Królu Złoty. Teraz za to mam taki

```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 33, in test_test_logout
    self.assertEqual(r3.status_code, 401)
AssertionError: 200 != 401
```

**Comment by moty-daft** [comment]
@gignacy 
Masz info w Trace: 200 != 401.
To oznacza, że zwracasz 200, a apka oczekuje że zwrócisz 401.

**Comment by gignacy** [comment]
Wcześniej do testów wyprintowałem ` @basic_auth.required ` ...

Dzięki! :)

**Comment by gignacy** [comment]
A o co chodzi w zadaniu czwartym, że ` 'id=greeting' ` ?

**Comment by moty-daft** [comment]
@gignacy 
Jeśli chodzi o to, że nie przechodzi testów, to było już zgłoszenie, sprawdź tu: https://github.com/daftcode/daftacademy-python_levelup-spring2019/issues/12
A jeśli chodzi o coś innego, to sprecyzuj proszę pytanie :)

PS
To już nie dotyczy tego wątku (tu jest zadanie 3, a nie 4)

**Comment by gignacy** [comment]
OK. dziękuję bardzo za pomoc :)
