### ISSUE TITLE
Deploy'owy armagedon 3.2

### ISSUE THREAD

**Issue by Piotr296** [daftcode/daftacademy-python_levelup-spring2019#14]
Mój kod wygląda sobie tak:

from flask import Flask, flash, redirect, render_template, request, session
import os

app = Flask(__name__)

@app.route('/')
def home():
    if not session.get('logged_in'):
        return render_template('login.html')

    else:
        return "Hello Boss!"

@app.route('/login', methods=['POST'])
def do_admin_login():
    if request.form['password'] == 'TuN3L' and request.form['username'] == 'TRAIN':
        session['logged_in'] = True
        return redirect('/hello')

    else:
        flash('wrong password!')
        return home()

if __name__ == "__main__":
    app.secret_key = os.urandom(12)
    app.run(debug=True, host='0.0.0.0', port=4000)

Ale po postawieniu apki, po kliknięciu w "Log in" mam 500 (błąd serwera), zaś po przejściu do ...herokuapp.com/login mam "Method Not Allowed. The method is not allowed for the requested URL."

Z czego to może wynikać?

**Comment by mateusz94** [comment]
@Piotr296: Wpisując URL w przeglądarce i klikając enter używasz metody GET, stąd odpowiedź serwera „Method Not Allowed. The method is not allowed for the requested URL” (@app.route('/login', methods=['POST'])).

W poleceniu 3.2 jest wskazanie, żeby używać BasicAuth, a nie formularza.

Sam błąd serwera (500), nie jestem w stanie powiedzieć z tej perspektywy.  Proponuję zajrzeć w logi, tu link do opisu jak to zrobić: https://devcenter.heroku.com/articles/logging

**Comment by Piotr296** [comment]
Dzięki!
Faktycznie, po ogarnięciu się z BasicAuth wszystko poszło.

**Comment by mateusz94** [comment]
To zamykam temat :rocket:
