### ISSUE TITLE
3.4

### ISSUE THREAD

**Issue by Piotr296** [daftcode/daftacademy-python_levelup-spring2019#15]
Jak wrzucić apkę na Heroku z przygotowanym templatem html?

Działam następująco:
1) tworze sobie /templates w folderze za apką i tworzę tam plik html do którego odwołuje się mój kod:
@app.route('/hello')
@requires_user_session
def hello():
return render_template('greeting.html', name=session['username'])

2) Jednak po dodaniu app.py do gita, html mi się nie dodaje. Czy muszę dodać to w jakiś specjalny/oddzielny sposób?

**Comment by mateusz94** [comment]
Cześć @Piotr296!

Wszystkie templatki muszą być w repozytorium, dlatego że aplikacja korzysta z plików tam zamieszczonych, a nie z Twojego prywatnego komputera.

Git i Github to inne rzeczy :D
