### ISSUE TITLE
tydzien 3, zad 5 i 6, JSONDecodeError

### ISSUE THREAD

**Issue by moty-daft** [daftcode/daftacademy-python_levelup-spring2019#16]
Hej,

Mam problem z przejściem testów, gdzie zwracane sa JSONy. Konkretnie:
Zadanie 5. get_trains (pozostałe testy przechodzą)
Zadanie 6. delete_trains i get_train

We wszystkich przypadkach widzę błąd:
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Nie wiem w jakiej formie oczekiwane są te JSONy w testach, dlatego używam dwóch podejść ale żadne z nich nie przechodzi:
w zadaniu 5 używam json.dumps i zwracam nagłówek text/html
w zadaniu 6 używam jsonify i zwracam nagłówek application/json

Moja apka:
http://moty-w3.herokuapp.com/

Byłabym wdzięczna za jakieś sugestie jeśli ktoś ma pomysł, gdzie może być błąd.
Albo jeśli komuś przechodzą te testy, to chętnie sprawdzę w postmanie jaka zwracacie odp i porównam ze swoja.

Z góry dzięki i pozdrawiam :)
//Marta

**Comment by mateusz94** [comment]
Cześć @moty-daft,

Odpowiedź na ścieżce /trains?format=json

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/trains/uuid_14?format=json">/trains/uuid_14?format=json</a>.  If not click the link.
```

1. To nie jest json
2. Nie ma tam informacji o pociągach :(

**Comment by Piotr296** [comment]
Ja mam trochę inny problem. W zadaniu 5 przechodzi mi test get_trains, a nie przechodzi mi post_trains.. Tylko nie wiem dlaczego, bo moja apka otrzymuje tego posta:
![obraz](https://user-images.githubusercontent.com/42346616/55236282-e9be1580-522f-11e9-9f0c-4dabb3e6d336.png)

Gdzie może leżeć problem?

**Comment by mateusz94** [comment]
@Piotr296:
Dzieje się tak, ponieważ struktura jsona nie zgadza się z tym przedstawionym w treści zadania.

**Comment by przemko0** [comment]
@mateusz94, mam podobny problem z testem get_trains w 3.5, czy coś tu jest źle, url do mojej appki  https://flask-daftcode.herokuapp.com/ ?
![image](https://user-images.githubusercontent.com/9726792/55249308-0d8f5480-524c-11e9-8dda-a31d5c64855f.png)
![image](https://user-images.githubusercontent.com/9726792/55249328-18e28000-524c-11e9-9c71-d59e9c9b720c.png)

**Comment by mateusz94** [comment]
@irqize : 
podaj proszę opis do tych obrazków.

**Comment by przemko0** [comment]
@mateusz94 GET /trains?format=json i GET /trains

**Comment by moty-daft** [comment]
W swojej apce zauważyłam, że na ścieżce GET /trains w request nie ma query string, w szczególności nie ma oczekiwanego "format=json". Nie wiem, czy nie wysyła go apka testująca, czy gdzieś po drodze się gubi ten parametr, ale go nie ma po prostu i stąd jest ten błąd parsowania JSONa.

**Comment by moty-daft** [comment]
@mateusz94 
W zad 5. widzę już poprawiony query_string, teraz test przechodzi, dzięki :)
W zad 6. natomiast jest ten sam problem - również na ścieżce GET /trains. Możecie to też poprawić?
Dzięki i pozdrawiam,
//Marta

**Comment by KrystianKurek** [comment]
Czy komuś się udało ominąć ten błąd w 6 zadaniu?

**Comment by moty-daft** [comment]
Hej,
To zależy, jaki masz błąd. U mnie chodziło o parsowanie, bo test próbuje parsować odp XML jako JSON. W tej sytuacji wystarczy, że odpowiesz na ścieżce GET /trains JSONem zamiast XMLem.

**Comment by KrystianKurek** [comment]
dostaję coś takiego: 
self.assertEqual(response.status_code, 204)
AssertionError: 404 != 204
wiem co to znaczy 404, ale ja nie wiem nawet jakie zapytanie zwraca ten kod, bo nie ma żadnej wiadomości zwrotnej, więc nie mam pojęcia co poprawić

**Comment by moty-daft** [comment]
Test sprawdza, czy zwracasz 204. Wydaje mi się, że to było przy usuwaniu, czyli przy DELETE. Spróbuj po usunięciu pociągu dać response z kodem http 204. Jeśli nie pomoże, to daj znać.

**Comment by KrystianKurek** [comment]
Dobra to było coś innego. Dzięki za pomoc.

**Comment by sBwin1** [comment]
Pomógłby ktoś znaleźć błąd w moim rozwiązaniu do zadania 6 :D?
Przy delete dostaje taki sam komunikat jak w pierwszym poście tj. 

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Mój kod służący do usuwania wygląda nastepująco: 
if request.method == "DELETE": 
      del data[id]
      with open('resources/trains.json', 'w') as f:
	    json.dump(data, f)
	return jsonify({"message": ""}), 204

**Comment by moty-daft** [comment]
Spóbuj zmienić funkcję na ścieżce GET /trains (wersja bez format=json) tak, żeby zwracała JSON zamiast XML. Twoja funkcja na DELETE wygląda OK, więc pewnie chodzi o to samo co było u mnie.

**Comment by sBwin1** [comment]
Ok, przeszło, dzięki!. Ale mimo wszystko słabo sprecyzowane zadanie według mnie i trochę czasu się straciło, mimo, że działało ok.
