### ISSUE TITLE
Problem z testem Wykład 4 zad 1

### ISSUE THREAD

**Issue by cv16r5** [daftcode/daftacademy-python_levelup-spring2019#18]
W zadaniu pierwszym przy ostatnim teście poprawności danych występuje mi następujący błąd:
Traceback (most recent call last): File "/home/runner/unit_tests.py", line 51, in test_method_returns_good_data self.assertEqual(data[100], 'Abraham, Martin And John') AssertionError: ['Absolute Zero'] != 'Abraham, Martin And John'

W moim jsonie "Abraham, Martin And John" znajduje się na pozycji 98. Skąd może wynikać taka różnica?

**Comment by julianno12** [comment]
Wynika z tego, że sqllite3 jest case sensitive podczas ustawiania kolejności utworów, jest coś takiego jak collate nocase.

**Comment by koseq** [comment]
Ja się podepnę pod pytanie, po dodaniu COLLATE NOCASE mam następujący błąd:

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 51, in test_method_returns_good_data
    self.assertEqual(data[100], 'Abraham, Martin And John')
AssertionError: ['Abraham, Martin And John'] != 'Abraham, Martin And John'

Ktoś wie o co tu chodzi?

**Comment by koseq** [comment]
> Ja się podepnę pod pytanie, po dodaniu COLLATE NOCASE mam następujący błąd:
> 
> Traceback (most recent call last):
> File "/home/runner/unit_tests.py", line 51, in test_method_returns_good_data
> self.assertEqual(data[100], 'Abraham, Martin And John')
> AssertionError: ['Abraham, Martin And John'] != 'Abraham, Martin And John'
> 
> Ktoś wie o co tu chodzi?

już wiem - nie zauważyłam zagnieżdżonych nawiasów ;)

**Comment by Piotr296** [comment]
Jakich zagnieżdżonych nawiasów? Mam ten sam problem.

**Comment by Piotr296** [comment]
Roboczo obszedłem problem.
Ale chętnie poznam właściwe rozwiązanie - muszę napisać SQLka, który ignoruje mi nawiasy? Czy co?

**Comment by piotrowskamjr** [comment]
Nie wiem czy jest możliwe zapytanie, które zignoruje zagnieżdżone listy, bo wyniki zwracają się wierszami. Ja po prostu obrobiłam zwrotkę kodem pythonowym :)

**Comment by mateusz94** [comment]
@Piotr296 : Takie rozwiązanie nie jest zalecane.

W odpowiedzi na zapytanie: GET URL/tracks oczekujemy listy utworów, a nie listę list utworów.

Metoda `fetchall()` zwraca listę krotek. Nie możesz napisać SQLki, która ignoruje nawiasy, ponieważ używając słowa: select oczekujesz zwrócenia listy wierszy, gdzie wiersze reprezentowane są jako krotki.

Obrazowo:

Mamy tabelę student i w niej kilkanaście pól. Potrzebuję mieć informacji o id studenta i jego imieniu. Dlatego wykonuję zapytanie:
`SELECT` id, name FROM student;`
Ii otrzymuję odpowiedź w stylu:

```
[
    (1, "Mateusz"),
    (2, "Piotr"),
    (3, "Piotr"),
]
```

Gdybym zapytał tylko o imię, to i tak dostanę listę krotek:

```
[
    ("Mateusz", ),
    ("Piotr", ),
    ("Piotr", ),
]
```

stąd pochodzi to 'zagnieżdżenie' wspomniane przez @koseq
