### ISSUE TITLE
Wykład 4 zadanie 3 testy

### ISSUE THREAD

**Issue by julianno12** [daftcode/daftacademy-python_levelup-spring2019#19]
Dostaję takie błędy w testach w zadaniu 3. Czy ktoś wie o co może chodzić ?
![Test](https://user-images.githubusercontent.com/38077316/55363551-af79a000-54dd-11e9-9d75-31d6e787e716.PNG)

**Comment by mateusz94** [comment]
Cześć @julianno12,
tego testu nie zdążyłem wrzucić podczas wykładu.
Już powinno być w porządku.
