### ISSUE TITLE
Problem z zadaniem 3 (kodowanie znaków?)

### ISSUE THREAD

**Issue by RafalKornel** [daftcode/daftacademy-python_levelup-spring2019#2]
Cześć!
Napotkałem problem robiąc trzecie zadanko, mianowicie repl.it wypluwa coś takiego:

`Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 20, in test_show_data_simple_case
    self.assertEqual(response.json(), data)
AssertionError: {'hejka': 'sportowe', 'świry': 'True'} != '{"hejka": "sportowe", "\\u015bwiry": "True"}'`

Tymczasem program który wkleiłem poniżej zwraca '{'key' : 'valueł'}', zatem to co (raczej) powinien. Dodam jeszcze że moja funkcja na heroku zwraca stringa. Gdzie robię błąd?

>import requests
>
> def test_function():
payload = {'key' : 'valueł'}
r = requests.post('http://test-appliaction.herokuapp.com/show_data', json = payload)
print(r.text)
return r.text
>
>test_function()

**Comment by Moribund7** [comment]
Dodam, że jeśli ktoś ma podobny problem z tym zadaniem to dodanie funkcji json.dumps(data) (przynajmniej tak było w moim przypadku) może pomóc.
