### ISSUE TITLE
Tydzień 4 zadanie 2

### ISSUE THREAD

**Issue by RafalKornel** [daftcode/daftacademy-python_levelup-spring2019#20]
Moja aplikacja zwraca to co powinna, przynajmniej w przypadku AC/DC :p
W przypadku testu wypluwa coś takiego, brakuje 10 recordów.
![image](https://user-images.githubusercontent.com/38111105/55435482-4015b600-559a-11e9-8c89-418eb1a54525.png)

Ktoś wie o czym mogę zapominać? 

Tak wygląda zapytanie: 

`ret = db.execute('SELECT name FROM tracks WHERE composer = ? ORDER BY name', (artist,)).fetchall()`

Dla porównania, apka zwraca to dla AC/DC:

> [
  "Bad Boy Boogie", 
  "Dog Eat Dog", 
  "Go Down", 
  "Hell Ain't A Bad Place To Be", 
  "Let There Be Rock", 
  "Overdose", 
  "Problem Child", 
  "Whole Lotta Rosie"
]

**Comment by koseq** [comment]
Musisz dopasować wykonawców z tabeli artists (czyli zrobić 2 JOINy artists->albums->tracks), wtedy wynik jest poprawny i przechodzi testy.

**Comment by RafalKornel** [comment]
Bardzo dziękuję, nie pomyślałbym o tym
