### ISSUE TITLE
Zadanie 4.2

### ISSUE THREAD

**Issue by koseq** [daftcode/daftacademy-python_levelup-spring2019#21]
Jak dokładnie mają działać endpointy? Rozumiem to tak: /tracks ma zwracać wszystkie utwory, a /track/artist utwory konkretnego wykonawcy. Jak testuje w przeglądarce, to wszystko wydaje się być ok, a testy zwracają mi 2 błędy:

- method_returns_18_elements
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 41, in test_method_returns_18_elements
    self.assertEqual(len(data), 18)
AssertionError: 3503 != 18

- method_returns_good_data
ten sam błąd

Jakiś pomysł, co robię źle? Baza danych na pewno nie jest zmieniona.

**Comment by koseq** [comment]
Już wiem ;) zamykam

**Comment by Piotr296** [comment]
Zechciałbyś się podzielić jak to działa :-)?

**Comment by koseq** [comment]
Jasne ;) Tylko o co dokładnie pytasz?

**Comment by Piotr296** [comment]
Mam sobie taki kod:

@app.route('/tracks/string:artist', methods=['GET'])
def tracks_list(artist):
db = get_db()
cursor = db.cursor()
artist = str(artist)
data = cursor.execute("""
SELECT tracks.name FROM tracks
JOIN albums ON tracks.albumid = albums.albumid
JOIN artists ON albums.artistid = artists.artistid
WHERE artists.name = (?) ORDER BY tracks.name
""", (artist,)).fetchall()
(...)

Apka działa i ładuje się na stronie, ale zwraca mi pustą listę: https://wyklad4zadanie2.herokuapp.com/tracks/Asspect

Pytanie moje jest: jak prawidłowo przekazać placeholder w approute i w treści samego zapytania?

**Comment by koseq** [comment]
też próbowałam najpierw zrobić to w ten sposób, okazuje się jednak, że artist trzeba przekazać najzwyklejszym query stringiem (tak samo jak kolejne parametry z następnych zadań).  

czyli np. taka ścieżka powinna ci zwracać utwory AC/DC: /tracks?artist=AC/DC

**Comment by Piotr296** [comment]
I jak to zrobić? 
Jak dopisałem w kodzie: request.args.get('artist') to dalej nie działa..

**Comment by koseq** [comment]
Generalnie nie ma mnie w domu i nie mam jak zajrzeć do swojego kodu.

Ale z tego co mi przychodzi do głowy - nie masz tu (request.args.get('artist')) domyślnej wartości dla artist, powinno być request.args.get('artist', None). Potem robisz ifa i różne zachowania w zależności od tego, czy w urlu jest artist czy nie (albo lista wszystkich utworów albo utworów danego wykonawcy).

**Comment by Piotr296** [comment]
Dobra, dałem sobie radę :-) Dzięki! Teraz mam problem z czwartym :P

**Comment by koseq** [comment]
Ja z czwartym się najdłużej męczyłam - miałam literówkę w request.get_json()['jakis tam klucz'] - wtedy rzuca bad request

**Comment by Piotr296** [comment]
Wzorowałem się na Tobie:
https://pastebin.com/BkwzmA6M

request.get_json() powinien przyjmować jakieś argumenty?

**Comment by koseq** [comment]
u mnie ten kod wyglądał mniej więcej tak:
json_data = request.get_json()
a potem np. album_id = json_data['album_id'] itd 
edit: jestem nieprzytomna dzisiaj, teraz zauważyłam że przez przypadek wrzuciłam do argumentu, już jest ok

A co ci nie działa?

**Comment by Piotr296** [comment]
Podmieniłem kody:
@app.route('/tracks', methods=['GET', 'POST'])
def tracks_list():
    db = get_db()
    cursor = db.cursor()

    artist = request.args.get('artist')
    limit = request.args.get('per_page')
    page = request.args.get('page') or 1

    if request.method =='GET' and limit is not None and page is not None:
        page = int(page) - 1
        offset = int(page) * int(limit)
        if artist is not None:
            data = cursor.execute('''SELECT tracks.name FROM tracks
                                    JOIN albums on tracks.albumid=albums.albumid
                                    JOIN artists on albums.artistid=artists.artistid 
                                    WHERE artists.name= (?) COLLATE NOCASE ORDER by tracks.name
                                    LIMIT (?) OFFSET (?)''', (artist, limit, offset))
        else:
            data = cursor.execute('''SELECT name FROM tracks 
                                    ORDER BY tracks.name COLLATE NOCASE
                                    LIMIT (?) OFFSET (?);'''.format(limit, offset))
        return jsonify([row[0] for row in data.fetchall()])

    elif request.method == 'POST':

        json_data = request.get_json()
        if json_data == None:
            cursor.close()
            return 400
        else:
            album_id = json_data['album_id']
            media_type_id = json_data['media_type_id']
            genre_id = json_data['genre_id']
            name = json_data['name']
            composer = json_data['composer']
            milliseconds = json_data['milliseconds']
            bbytes = json_data['bytes']
            price = json_data['price']
            cursor.execute('''INSERT INTO tracks (name, albumid, mediatypeid, genreid, composer, milliseconds, bytes, unitprice) 
                           VALUES (?,?,?,?,?,?,?,?)''',(name, album_id, media_type_id, genre_id, composer, milliseconds, bbytes, price))
            data = cursor.execute('''SELECT * FROM tracks
                                     WHERE trackid = (SELECT MAX(trackid)  FROM tracks)''')
            cursor.close()
            return jsonify(data), 200

Podmieniłem na json_data i dalej żaden test mi nie przechodzi :(
