### ISSUE TITLE
wyklad 4 zadanie 2

### ISSUE THREAD

**Issue by ularom234** [daftcode/daftacademy-python_levelup-spring2019#22]
Moja aplikacja działa na komputerze, kiedy wysyłam ją na heroku pojawia mi się taka informacja:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

Po wpisaniu tej komendy problem się nie rozwiązuje. 
Na wykładzie znalazłam takie rozwiązanie:

SQLite na Heroku? Nie jest to najlepszy pomysł https://devcenter.heroku.com/articles/sqlite3
Wystarczy wypushować dodatkowo plik z bazą danych na Heroku
Problem: Wprowadzane w nim zmiany będą wymazywane, przynajmniej raz na 24h - po każdym deployu, restarcie i co około 24h z powodu tego , jak Heroku zarządza swoimi dynos
Co z tym robimy? Na tych zajęciach nic
Dobre rozwiązanie? Korzystanie z Heroku Postgres https://elements.heroku.com/addons/heroku-postgresql zamiast z sqlite ale to już na kolejnych zajęciach

Jak rozwiązać ten problem teraz?

**Comment by mateusz94** [comment]
@ularom234:
To co jest opisane na wykładzie, czyli wrzucasz plik z bazą danych na zdalne repozytorium.

Wpisując komendę: `heroku logs --tail` nie rozwiązujesz problemu, tylko sprawdzasz co poszło nie tak i dopiero na tej podstawie robisz dobrze.

**Comment by ularom234** [comment]
@mateusz94 
To są moje komendy podczas wrzucania aplikacji:

git init
heroku git:remote -a muzzy
git add Procfile app.py requirements.txt chinook.db
git commit -am "make it better"
git push heroku master

Więc wrzucam bazę na repozytorium. A i tak zwraca błąd. Dodam, że pierwsze zadanie przeszło.

**Comment by mateusz94** [comment]
@ularom234, opis komend, który przedłożyłeś niewiele mówi o tym dlaczego otrzymujesz `application error`. 
Jeśli nie sprawdzisz logów i nie zastosujesz się do tego co tam jest napisane, to nie rozwiążesz problemu. Zakładam, że problemem jest literówka, niepoprawne wcięcie lub niepoprawny import w pliku app.py.

**Comment by ularom234** [comment]
Program działa mi na komputerze.

Zwraca mi dwa błędy:

2019-04-03T13:45:23.679608+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=muzzyka.herokuapp.com request_id=4eb77991-bd17-45fa-8dc9-e328c1f52aaa fwd="89.64.3.215" dyno= connect= service= status=503 bytes= protocol=https

2019-04-03T13:45:23.957168+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=muzzyka.herokuapp.com request_id=19afcda4-56cc-4fa6-b9c0-89bc0a7216e7 fwd="89.64.3.215" dyno= connect= service= status=503 bytes= protocol=https

**Comment by mateusz94** [comment]
@ularom234: Podpowiem: dodałaś coś między jednym zadaniem a drugim.

**Comment by syzymon** [comment]
Mam problem z testami w zadaniu 4.2, czy aby na pewno taki request `GET /tracks?artist=AC%2FDC` powinien zwrócić 18 elementów, a nie 8? 

```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 40, in test_method_returns_18_elements
    self.assertEqual(len(data), 18)
AssertionError: 8 != 18
```

Takie coś zwraca mi repl.it, sprawdziłem w logach heroku i jedyne zapytania jakie dostaję to są właśnie takie.

**Comment by mateusz94** [comment]
@syzymon : tak, możesz to sprawdzić ręcznie.

**Comment by wkondrusiewicz** [comment]
> @syzymon : tak, możesz to sprawdzić ręcznie.

Dostaję identyczny błąd jak @syzymon i nie za bardzo wiem czemu, ponieważ nawet ręcznie licząc pozycje w bazie danych, np za pomocą DBeaver'a, dostaję 8 utworów AC/DC a nie 18. Nie za bardzo wiem skąd miałoby się wziąć te dodatkowe 10 utworów, ponieważ nawet ich nie widziałem w bazie danych.

**Comment by mateusz94** [comment]
@wkondrusiewicz: Nie wiem jak liczysz te utwory ale może mamy różne bazy?
W bazie powinny być utwory z tych płyt:
- `Let There Be Rock`
- `For Those About to Rock We Salute You`

**Comment by wkondrusiewicz** [comment]
> @wkondrusiewicz: Nie wiem jak liczysz te utwory ale może mamy różne bazy?
> W bazie powinny być utwory z tych płyt:
> 
> * `Let There Be Rock`
> * `For Those About to Rock We Salute 

Nie pomyślałem, że nazwie AC/DC może odpowiadać też inna nazwa np imiona wykonawców. Dziękuję.

**Comment by Piotr296** [comment]
Jak prawidłowo przekazać placeholder w @app.route i potem w zapytaniu? 
Jak sprawić, żeby wartością oczekiwaną był string? Nie mogę dojść do tego studiując wykład i szukając w sieci - będę wdzięczny za pomoc!

**Comment by mateusz94** [comment]
@Piotr296:
jeżeli chcesz mieć pewność, że dany obiekt jest stringem to go zrzutuj na stringa :3
`jakis_obekt = str(jakis_obiekt)`

jak prawidłowo przekazać placeholder w zapytaniu sql, opisane jest np tu: [docs](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.execute)

tego pytania o placeholder w @app.route to nie rozumiem, rozwiń proszę.

**Comment by Piotr296** [comment]
@mateusz94 
@app.route('/tracks/<int:artist>', methods=['GET']) Jak tutaj przekazać nasz oczekiwany parametr artist? Próbowałem z str:artist, ale nie działa..
