### ISSUE TITLE
4.4

### ISSUE THREAD

**Issue by koseq** [daftcode/daftacademy-python_levelup-spring2019#23]
Hej, mam problem z zadaniem 4 - przy dwóch pierwszych testach wyrzuca mi _400 Bad Request_.
Zupełnie nie wiem o co może chodzić. Fragment kodu odpowiedzialny za POST wygląda tak:

`
     elif request.method == 'POST':

		json_data = request.get_json()
		if json_data == None:
			cursor.close()
			return 400
		else:
			album_id = request.form['album_id']
			media_type_id = request.form['media_type_id']
			genre_id = request.form['genre_id']
			name = request.form['name']
			composer = request.form['composer']
			milliseconds = request.form['milliseconds']
			bbytes = request.form['bytes']
			price = request.form['price']
			cursor.execute('''INSERT INTO tracks (name, albumid, mediatypeid, genreid, composer, milliseconds, bytes, unitprice) 
               			   VALUES (?,?,?,?,?,?,?,?)''',(name, album_id, media_type_id, genre_id, composer, milliseconds, bbytes, price))
			data = cursor.execute('''SELECT * FROM tracks
    								 WHERE trackid = (SELECT MAX(trackid)  FROM tracks)''')
			cursor.close()
			return jsonify(data), 200`

Też super by było wiedzieć co sprawdza ostatni test _method_invalid_json_ i dlaczego przechodzi ;)

**Comment by mateusz94** [comment]
@koseq : 
Twoja aplikacja ciągle zwraca 400 :D to dlatego. Sprawdź samemu co zwraca. Użyj postmana, czy httpie, czy innego narzędzia.

**Comment by koseq** [comment]
zamykam, okazało się, ze to literówka w jsonie

**Comment by Piotr296** [comment]
@koseq czy obsługujesz także metodę GET?
