### ISSUE TITLE
wyklad 4 zadanie 3

### ISSUE THREAD

**Issue by ularom234** [daftcode/daftacademy-python_levelup-spring2019#24]
moja aplikacja nie przechodzi testu:
method_returns_5_elements
method_returns_good_data

dlaczego? moim zdanie wywołanie działa prawidłowo: 
https://muzzy.herokuapp.com/tracks?artist=AC/DC&per_page=5&page=1

**Comment by ularom234** [comment]
jednak juz zadziałało

**Comment by wolodev** [comment]
Powiedziałbyś w czym tkwił problem? Moja aplikacja zwraca dokładnie to co twoja a jednak nadal nie przechodzą mi te dwa testy
