### ISSUE TITLE
4.3

### ISSUE THREAD

**Issue by wolodev** [daftcode/daftacademy-python_levelup-spring2019#25]
Cześć, mam problem z zadaniem 4.3 gdyż dostaje dwa błędy:
method_returns_5_elements
method_returns_good_data
Nie mogę jednak znaleźć przypadku kiedy moja aplikacja zwracałaby złe dane lub ich ilość, sprawdzałem sobie w DBeaverze i wszystko mi się zgadza.
Link do aplikacji: https://testowanieapkiweflasku.herokuapp.com/tracks?artist=AC/DC&per_page=5&page=2
Mój kod:

```python
@app.route('/tracks', methods=['GET'])
def tracks_list():
    db = get_db()
    cursor = db.cursor()
    user = request.args.get('artist')
    limit = request.args.get('per_page')
    page = request.args.get('page')
    if user is not None and (page is None or limit is None):
        data = cursor.execute('''SELECT tracks.name FROM tracks
                                     JOIN albums on tracks.albumid=albums.albumid
                                     JOIN artists on albums.artistid=artists.artistid WHERE artists.name=\'{}\' COLLATE NOCASE ORDER by tracks.name'''.format(
            user))
    else:
        data = cursor.execute('SELECT name FROM tracks ORDER BY tracks.name')

    if limit is not None and page is not None:
        page = int(page) - 1
        offset = int(page) * int(limit)
        if user is not None:
            data = cursor.execute('''SELECT tracks.name FROM tracks
                                                 JOIN albums on tracks.albumid=albums.albumid
                                                 JOIN artists on albums.artistid=artists.artistid WHERE artists.name=\'{}\' COLLATE NOCASE ORDER by tracks.name
                                                 LIMIT {} OFFSET {};'''.format(user, limit, offset))
        else:
            data = cursor.execute('''SELECT name FROM tracks ORDER BY tracks.name COLLATE NOCASE
                                                 LIMIT {} OFFSET {};'''.format(limit, offset))
    return jsonify([row[0] for row in data.fetchall()])

```

**Comment by JakubNaskretski** [comment]
Cześć, to ja się podepne.
Również mam błąd:

"method_returns_good_data:"
"Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 66, in test_method_return_offset_data
    self.assertEqual(len(data), 3)
AssertionError: 5 != 3"

o ile dobrze patrzę na loggi to zapytanie wygląda tak:

"/tracks?artist=AC%2FDC&per_page=5"

Mógł by mnie ktoś może upewnić jak to czytać ?
Mój kod zwracam 5 selectów, a rozumiem że testy spodziewają się 3, przy zapytaniu o 5 ?

Z góry dzięki

**Comment by JakubNaskretski** [comment]
Cześć, to ja się podepne.
Również mam błąd:

"method_returns_good_data:"
"Traceback (most recent call last):
File "/home/runner/unit_tests.py", line 66, in test_method_return_offset_data
self.assertEqual(len(data), 3)
AssertionError: 5 != 3"

o ile dobrze patrzę na loggi to zapytanie wygląda tak:

"/tracks?artist=AC%2FDC&per_page=5"

Mógł by mnie ktoś może upewnić jak to czytać ?
Mój kod zwracam 5 selectów, a rozumiem że testy spodziewają się 3, przy zapytaniu o 5 ?

Z góry dzięki

**Comment by JakubNaskretski** [comment]
Cześć, to ja się podepne.
Również mam błąd:

"method_returns_good_data:"
"Traceback (most recent call last):
File "/home/runner/unit_tests.py", line 66, in test_method_return_offset_data
self.assertEqual(len(data), 3)
AssertionError: 5 != 3"

o ile dobrze patrzę na loggi to zapytanie wygląda tak:

"/tracks?artist=AC%2FDC&per_page=5"

Mógł by mnie ktoś może upewnić jak to czytać ?
Mój kod zwracam 5 selectów, a rozumiem że testy spodziewają się 3, przy zapytaniu o 5 ?

Z góry dzięki

**Comment by Kuba2286** [comment]
Cześć, to ja się podepne.
Również mam błąd:

"method_returns_good_data:"
"Traceback (most recent call last):
File "/home/runner/unit_tests.py", line 66, in test_method_return_offset_data
self.assertEqual(len(data), 3)
AssertionError: 5 != 3"

o ile dobrze patrzę na loggi to zapytanie wygląda tak:

"/tracks?artist=AC%2FDC&per_page=5"

Mógł by mnie ktoś może upewnić jak to czytać ?
Mój kod zwracam 5 selectów, a rozumiem że testy spodziewają się 3, przy zapytaniu o 5 ?

Z góry dzięki

**Comment by wolodev** [comment]
Problem rozwiązany, polegał na tym żeby przyjąć page=1 jeśli podane było tylko per_page w querystringu, a nie ignorować ten przypadek jako mający za mało argumentów. Zamknę gdy padnie odpowiedź na pytanie @Kuba2286

**Comment by mateusz94** [comment]
@Kuba2286 wydaję mi się, że nie patrzysz na odpowiedni log.

**Comment by mateusz94** [comment]
@Kuba2286 wydaję mi się, że nie patrzysz na odpowiedni log.

**Comment by JakubNaskretski** [comment]
@mateusz94  Wygląda na to że nie :D Jednak mój błąd w kodzie i rozwiązanie kolegi wyżej mi podpowiedziało co zrobic. Dzięki.
