### ISSUE TITLE
Wykład 4.2

### ISSUE THREAD

**Issue by Piotr296** [daftcode/daftacademy-python_levelup-spring2019#26]
Jak prawidłowo przekazać placeholder i endpoint? Czy w @app.route powinienem coś dodać?
Niestety kod mi nie przechodzi, nawet 200.

@app.route('/tracks/<string:artist>', methods=['GET'])
def tracks_list(artist):
    db = get_db()
    cursor = db.cursor()
    artist = str(artist)
    data = cursor.execute("""
    SELECT tracks.name FROM tracks
    JOIN albums ON tracks.albumid = albums.albumid
    JOIN artists ON albums.artistid = artists.artistid
    WHERE artists.name = (?) ORDER BY tracks.name
    """, (artist,)).fetchall()

**Comment by wolodev** [comment]
Ja użyłem request.args.get('artist') i w app.route nic nie dodawałem, zostaje samo '/tracks'. Jeśli nie zostanie podana wartość dla artist w query stringu to request.args.get zwróci None.

**Comment by Piotr296** [comment]
Dzięki!
