### ISSUE TITLE
wyk4 zad4

### ISSUE THREAD

**Issue by ularom234** [daftcode/daftacademy-python_levelup-spring2019#27]
Cześć, mam problem z tym:
  - niestworzenie obiektu powinno objawić się zwróconym kodem 400 jeśli przesłane dane będą niekompletne

- próbuję to zrobić w ten sposób :
    json_data = request.get_json()
    #print(json_data)

    if not json_data:
        return 400
Za każdym razem zwraca mi błąd 500. Jak powinna wyglądąć ta część? Co dokładnie chcieli by w zadaniu? Ktoś już to przeszedł?

**Comment by Piotr296** [comment]
Mam ten sam problem, tylko robię to tak:
 elif request.method == 'POST':
   json_data = request.get_json()
        if json_data == None:
            cursor.close()
            return 400

A przechodzą Ci pierwsze dwa testy?
Bo mi nie wiem dlaczego nie chcą przejść przy takim kodzie:
https://pastebin.com/BkwzmA6M

**Comment by ularom234** [comment]
ja pobieram dane tak:
album_id = json_data.get('album_id')

i w tym ostatnim data (linijka 62,63) dodała bym fetchone()
i powinno Ci przejść test

**Comment by Piotr296** [comment]
O! Rzeczywiście brakowało fetchone(). Po dodaniu przeszły mi dwa pierwsze testy, ale teraz trzeci mi wisi (z kolei wcześniej tylko on mi przechodził).
Nie wiem czemu ten fragment tego nie załatwia?
        if json_data == None:
            cursor.close()
            return 400

**Comment by moty-daft** [comment]
Mi zadanie 4 przechodzi  przez testy.
Jeśli chodzi o ten case ze zwróceniem 400 to ja to rozumiem tak, że mogą przesłać JSON ale niepełny, np. tylko z trzema parametrami. Wtedy macie json_data wypełnione, ale dane są jednak niekompletne i trzeba zwrócić 400. Sprawdźcie bo może o to chodzi.

**Comment by Piotr296** [comment]
Dodałem taki statement:
if album_id is None or media_type_id is None or genre_id is None or name is None or composer is None or milliseconds is None or bbytes is None or price is None:
                cursor.close()
                return 400
Może nie najładniejszy, ale wciąż nie działa.

**Comment by moty-daft** [comment]
A jaki masz błąd? Czy działa Ci lokalnie? W sensie, jak wyślesz niekompletny JSON, to czy zwraca Ci 400?
Jeśli tak, to czy wgrywasz do testów nową bazę? Tam było napisane, że do przejścia przez testy w zadaniu 4 musi być czysta baza.

try:
    album_id = new_track['album_id']
    media_type_id = new_track['media_type_id']
    ...
except:
    return 'incomplete data', 400

**Comment by Piotr296** [comment]
W poście otrzymuje 404:
![obraz](https://user-images.githubusercontent.com/42346616/55675347-694b8480-58c1-11e9-8f4e-d58c940220cc.png)

**Comment by Piotr296** [comment]
Chociaż w teście mam 500:
![obraz](https://user-images.githubusercontent.com/42346616/55675358-aca5f300-58c1-11e9-8af4-0f737b13d1f9.png)

**Comment by moty-daft** [comment]
O, ciekawe. A lokalanie co ci zwraca?

**Comment by Piotr296** [comment]
Lokalnie zwraca mi 404

**Comment by Piotr296** [comment]
Tak to wygląda obecnie: https://pastebin.com/zkwRfW2p
Ściągnąłem specjalnie nową bazę dla pewności, ale dalej ten test mi nie przechodzi. Wcześniej to był jedyny test, który mi śmigał, ale nie wiem co się popsuło. Chciałem cofnąć wersję w gicie, ale coś mi się crachowało..

**Comment by moty-daft** [comment]
Ciekawe że lokalnie zwraca Ci 404. U mnie zwróciło 500 przy niekompletnym JSONie na Twoim kodzie.
Jak dodałam ten Twój długi if na koniec try:
![image](https://user-images.githubusercontent.com/48916388/55675763-30aea980-58c7-11e9-9047-8c984916f91f.png)
to zwraca mi teraz poprawnie 400:
![image](https://user-images.githubusercontent.com/48916388/55675770-59cf3a00-58c7-11e9-83d9-8dcb897762e1.png)

**Comment by moty-daft** [comment]
A już wiem czemu miałeś 404.
Miałeś inny adres: http://127.0.0.1:5000/tracks/?album_id=21

**Comment by Piotr296** [comment]
Ja już nie wiem co za czary się dzieją. Teraz jak ponownie ściągnąłem bazę danych, ponownie zrobiłem apkę na heroku, ponownie wszystko zdeployowałem, to kod mi nie przechodzi żadnego testu, a nic w nic nie zmieniłem xD

**Comment by Piotr296** [comment]
Skróciłem nieco kod, usunąłem niepotrzebne wątki, na razie próbuje przywrócić chociaż przechodzenie dwóch pierwszych testów..

import sqlite3
from flask import g, jsonify, request
from flask import Flask

DATABASE = 'chinook.db'
app = Flask(__name__)


def get_db():
    db = getattr(g, '_database', None)
    if db is None:
        db = g._database = sqlite3.connect(DATABASE)
    return db


@app.teardown_appcontext
def close_connection(exception):
    db = getattr(g, '_database', None)
    if db is not None:
        db.close()


@app.route('/tracks', methods=['GET', 'POST'])
def tracks_list():
    db = get_db()
    cursor = db.cursor()

    if request.method == 'POST':
        json_data = request.get_json()
        if json_data is None:
            cursor.close()
            return 400
        else:
            album_id = json_data.get('album_id')
            media_type_id = json_data.get('media_type_id')
            genre_id = json_data.get('genre_id')
            name = json_data.get('name')
            composer = json_data.get('composer')
            milliseconds = json_data.get('milliseconds')
            bbytes = json_data.get('bytes')
            price = json_data.get('price')
            if album_id is None or media_type_id is None or genre_id is None or name is None or composer is None or milliseconds is None or bbytes is None or price is None:
                return 'incomplete data', 400

            cursor.execute('''INSERT INTO tracks (name, albumid, mediatypeid, genreid, composer, milliseconds, bytes, unitprice)
                                          VALUES (?,?,?,?,?,?,?,?)''',
                           (name, album_id, media_type_id, genre_id, composer, milliseconds, bbytes, price))
            data = cursor.execute('''SELECT * FROM tracks
                                    WHERE trackid = (SELECT MAX(trackid)  FROM tracks)''').fetchone()
            cursor.close()
            return jsonify(data), 200


if __name__ == '__main__':
    app.run(debug=True)

**Comment by Piotr296** [comment]
Możecie sobie wyobrazić mnie krzyczącego "raaatuuuunku" z głębokiej studni, tymczasem lecę spać i bardzo dziękuje wszystkich za dotychczasową pomoc ^^! Jutro jeszcze spróbuje do tego przysiąść, wydaje mi się, że teraz to może być kwestia heroku, a nie mojej aplikacji bo mam 500 przy samym /tracks. Gdyby ktoś miał jakieś porady odnośnie kodu wyżej to byłbym mega wdzięczny!

**Comment by mateusz94** [comment]
Cześć @Piotr296, nie wiem na ile aktualny jest ten kod → https://pastebin.com/zkwRfW2p
ale na pewno nie obsługujesz w nim przypadku zapytania GET bez dodatkowych parametrów.

Masz tam:

```
if request.method =='GET' and limit is not None and page is not None:
     .....

elif request.method == 'POST':
     .....
```

i tu koniec obłsugi endpointu /tracks. Co będzie jak wykonywany program nie wejdzie w żaden w warunków? Twoja aplikacja odpowie kodem 500, bo zapytanie nie jest poprawnie obsłużone.

**Comment by ularom234** [comment]
myślę, że warto poczytać do tego ostatniego błędu by zwróciło 400

http://flask.pocoo.org/docs/0.12/patterns/apierrors/
