### ISSUE TITLE
5.2 i 3

### ISSUE THREAD

**Issue by ularom234** [daftcode/daftacademy-python_levelup-spring2019#31]
Czy ktoś mógłby mi powiedzieć dlaczego moja aplikacja nie działa? Jakiś pomysł?

**Comment by syzymon** [comment]
Jeśli chodzi o 5.2, to u mnie Twoja appka zwraca błąd:
`TypeError: cannot convert dictionary update sequence element #0 to a sequence`

w linijce:
`return jsonify(dict(row for row in tracks))` 

co raczej ma sens, ponieważ próbujesz rzutować iterable, którego 0 element jest pojedynczą wartością na dicta. Poza tym, wynik trzeba zwrócić raczej w formie listy dictów wrzuconej do JSON'a, a nie samego dicta. Co do samej serializacji pojedynczych obiektów z modelu, u mnie domyślne metody nie działały więc zrobiłem to ręcznie ale być może jest jakiś fajny sposób.

**Comment by ularom234** [comment]
ok a jak zmienię na jsonify(dict(tracks)), albo jsonify(tracks) to czy się już coś pojawia? w sensie cokolwiek zwraca?

bo domyślam się, że format może być nie taki jak trzeba, ale moja aplikacja na heroku pokazuje tylko 500 i nie wiem co robię źle i czego może to być wina.

na heroku mam wgraną bazę.

a na kompie zwraca mi:

 conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"

i teraz nie wiem na którym etapie mam błąd.. i jak wcześniejsze rozwiązać

**Comment by paw787878** [comment]
Jeśli chodzi o to password authentication failed to może chodzi o to, że zmieniłeś sobie hasło na postgresa, a to hasło powinon być w tym stringu "postgresql://postgres:postgres@localhost:5432/chinook" między ':' a '@'.

**Comment by ularom234** [comment]
o rzeczywiście zmieniłam a teraz mam:
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "chinook" does not exist

jakoś się ją załącza specjalnie? mam ją w tym samym folderze

**Comment by paw787878** [comment]
Tak załącza się. Chodzi o to, że nie ważne, że jest w ścieżce. Ma być tak, że ta baza danych jest dostępna przez url, czyli w przypadku tego lokalnego postgresa przez local host. To jest opisane w rozdziale
5. Setup bazy PostgreSQL lokalnie i na heroku
a dokładnie by mieć lokalnie dane i do nich dostęp robisz 
psql -h 127.0.0.1 -p 5432 -U postgres chinook < chinook_pg_serial_pk_proper_naming.sql
(w tym folderze gdzie masz ten plik chinook_pg_serial_pk_proper_naming.sql  pobrany z tamtąd gdzie piszą w wykładzie.

Tam jest też instrukcja jak dodać na heroku, jest to proces trochę inny. Przy czym jak go będziesz robił to  pamiętaj, że chyba najpierw trzeba coś poklikać w gui twojej apki heroku. Znalazłem stronkę gdzie piszą co poklikać

https://medium.com/@vapurrmaid/getting-started-with-heroku-postgres-and-pgadmin-run-on-part-2-90d9499ed8fb

A i jeszcze polecam spojrzeć sobie w dane przy pomocy dbeaver. Należy wówczas kliknąć na "kontakt" w dbeaverze (u góry po lewo),  i tam jest postgresql i tam się daje namiary na bazę danych.

**Comment by ularom234** [comment]
Popróbuję, dziękuję :)

**Comment by AlanRudzinski** [comment]
Czesc,
Macie jakies wskazowki jak zrobic te serializacje obiektow z modelu? Probowalem wielu rzeczy i nie udalo mi sie znalezc rozwiazania.

**Comment by ularom234** [comment]
właśnie do tego doszłam i też podczepiam się pod to pytanie

**Comment by ularom234** [comment]
znalazlam cos takiego, ale jeszcze nie zwraca tego co trzeba:
result_dict = [u.__dict__ for u in tracks.all()]
    return (result_dict)
wynik jednego (akurat 10):
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f1e4f676a50>, 'name': u'Fire In Space', 'album_id': 253, 'bytes': 536784757, 'unit_price': Decimal('1.99'), 'track_id': 3239, 'composer': None, 'media_type_id': 3, 'milliseconds': 2926593, 'genre_id': 20}]

**Comment by AlanRudzinski** [comment]
Pod tracks masz wstawione query? Bo ja mam cos takiego:
`db_session.query(models.Track).order_by(models.Track.milliseconds.desc()).limit(10)`
I jak probuje wygenerowac liste w taki sposob to dostaje:
AttributeError: 'Track' object has no attribute 'dict'

**Comment by FHoffmannCode** [comment]
apropo rzutowania obiektów sqlalchemy do dictów, polecam zapoznać się z następującym 'artykułem' - https://www.tutorialspoint.com/What-does-built-in-class-attribute-dict-do-in-Python

**Comment by FHoffmannCode** [comment]
> znalazlam cos takiego, ale jeszcze nie zwraca tego co trzeba:
> result_dict = [u.**dict** for u in tracks.all()]
> return (result_dict)
> wynik jednego (akurat 10):
> {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f1e4f676a50>, 'name': u'Fire In Space', 'album_id': 253, 'bytes': 536784757, 'unit_price': Decimal('1.99'), 'track_id': 3239, 'composer': None, 'media_type_id': 3, 'milliseconds': 2926593, 'genre_id': 20}]

dobrze znalazłaś, tylko jak wklejasz kod w postaci czystego tekstu to Ci zjadło podłogi wokół `__dict__` :P

```python
result_dict = [u.__dict__ for u in tracks.all()]
return (result_dict)
```
wynik jednego (akurat 10):
```python
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f1e4f676a50>, 'name': u'Fire In Space', 'album_id': 253, 'bytes': 536784757, 'unit_price': Decimal('1.99'), 'track_id': 3239, 'composer': None, 'media_type_id': 3, 'milliseconds': 2926593, 'genre_id': 20}]
```

jedyne co mi nie pasuje w Twojej metodzie to obecność klucza `_sa_instance_state` w Twoim słowniku

**Comment by ularom234** [comment]
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f1e4f676a50>, 'name': u'Fire In Space', 'album_id': 253, 'bytes': 536784757, 'unit_price': Decimal('1.99'), 'track_id': 3239, 'composer': None, 'media_type_id': 3, 'milliseconds': 2926593, 'genre_id': 20}

w słowniku istnieje coś takiego 'unite_price':**Decimal**('1.99')
jak sobie z tym poradzić?

wyrzuca mi taki błąd:
raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Decimal('1.99') is not JSON serializable

**Comment by ularom234** [comment]
jednak już sobie poradziłam

**Comment by ularom234** [comment]
dlaczego zapytanie z 5.3:
'''
        tracks = db_session.query(models.Track).join(models.Track.album).join(models.Album.artist).filter(models.Artist.name == art).order_by(models.Track.milliseconds.desc()).limit(10)
'''
zwraca mi pustą liste?
ogólnie to zapytanie wygląda dobrze:
'''
SELECT track.track_id AS track_track_id, track.name AS track_name, track.album_id AS track_album_id, track.media_type_id AS track_media_type_id, track.genre_id AS track_genre_id, track.composer AS track_composer, track.milliseconds AS track_milliseconds, track.bytes AS track_bytes, track.unit_price AS track_unit_price 
FROM track JOIN album ON album.album_id = track.album_id JOIN artist ON artist.artist_id = album.artist_id 
WHERE artist.name = %(name_1)s ORDER BY track.milliseconds DESC 
 LIMIT %(param_1)s
'''
ale tylko pusta liste zwraca mi lokalnie na heroku jest ok ale innej dlugosci, błąd jak ponizej

**Comment by ularom234** [comment]
i dlaczego moja aplikacja: https://muzzy2.herokuapp.com/longest_tracks
zwraca błąd w teście:

'''
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 21, in test_get_10_longest
    response_dict, expected_result
AssertionError: Lists differ: [{'album_id': 227, 'bytes': 1054423946, 'composer': Non[1873 chars]99'}] != [{'album_id': '227', 'bytes': '1054423946', 'composer':[2013 chars]99'}]

First differing element 0:
{'album_id': 227, 'bytes': 1054423946, 'composer': Non[132 chars].99'}
{'album_id': '227', 'bytes': '1054423946', 'composer':[146 chars].99'}

Diff is 5807 characters long. Set self.maxDiff to None to see it.
'''
skąd to się bierze skoro wygląda dobrze?
może jednak bierze się to z tego błędu co niby sobie poradziłam?

**Comment by konradorlinski** [comment]
Używaj proszę odpowiednich znaków do wstawianiu kodu (` zamiast '). Inaczej rozczytanie kodu jest bardzo utrudnione. Materiał: https://help.github.com/en/articles/creating-and-highlighting-code-blocks
