### ISSUE TITLE
Jak przywrócić bazę danych heroku do postaci początkowej

### ISSUE THREAD

**Issue by paw787878** [daftcode/daftacademy-python_levelup-spring2019#32]
Wydaje mi się, że warto dla naszego dobra mieć do testów bazę danych bez wstawionych nowych elementów. W jaki sposób można tą bazę danych cofnąć do początkowej postaci?

**Comment by koseq** [comment]
To sprawia wrażenie, jakby przy bezpłatnej wersji nie było takiej opcji:
![image](https://user-images.githubusercontent.com/39097446/55837687-64394000-5b22-11e9-8ef6-572fd5a44ed1.png)

**Comment by FHoffmannCode** [comment]
komenda którą załadowałeś bazę po raz pierwszy tak naprawdę służy głównie właśnie do przywracania bazy z backupu, jak najbardziej można to zrobić, po prostu odpalasz to samo polecenie jeszcze raz:

`heroku pg:backups:restore 'dump_url' DATABASE_URL --app NAZWA_TWOJEJ_APKI`

**Comment by FHoffmannCode** [comment]
btw testy specjalnie są tak napisane, że wcale nie musisz przywracać bazy do pierwotnego stanu o ile nie usuwałeś z niej żadnych wierszy nieutworzonych przez siebie
