### ISSUE TITLE
Termin pracy domowej

### ISSUE THREAD

**Issue by BielinskiLukasz** [daftcode/daftacademy-python_levelup-spring2019#33]
Cześć :)

Pamiętam, że termin z pracą domową jest do jutra, ale chciałem dopytać czy jest to standardowo 8 rano czy może do końca dnia? :)

**Comment by jdudzik98** [comment]
Na wykładzie padła godzina 8.00 :/

**Comment by BielinskiLukasz** [comment]
Oki, to oznacza długą noc. Dzięki :)

**Comment by magdakusiak** [comment]
Czy chodzi o wszystkie zadania z 5 wykładu ? Na replicie jest termin do 15.04.

**Comment by jfpio** [comment]
Termin jest na replit'cie do 15.04, ale mówili na wykładzie, że mamy termin do czwartku rano, aby mogli zebrać dane z liczby prac domowych, które zrobiliśmy i na tej podstawie przygotować certyfikaty, tak aby na poniedziałkowe zajęcia były już gotowe.

**Comment by magdakusiak** [comment]
Rozumiem , dzięki :)
