### ISSUE TITLE
5 zad 4

### ISSUE THREAD

**Issue by ularom234** [daftcode/daftacademy-python_levelup-spring2019#34]
https://muzzy2.herokuapp.com/artists

dlaczego moja aplikacja nie przechodzi testu, kiedy na postmanie zwraca wszystko prawidłowo?

**Comment by paw787878** [comment]
Spróbuj wrzucić try except w miejscu gdzie komunikujesz się z bazą danych.

**Comment by ularom234** [comment]
nic mi to nie zmieniło.
tak wygląda kod:

```
@app.route("/artists", methods=["POST"])
def artists():
    if request.method == "POST":
        return post_artists()
    abort(405)

def post_artists():
    data = request.json
    new_name = data.get("name")
    if new_name is None:
        abort(400)
        
    art = models.Artist(name = new_name)
    db_session.add(art)
    db_session.commit()

    artist = db_session.query(models.Artist).filter(models.Artist.name == new_name).first()
    result_dict = []
    result_dict.append(artist.__dict__)
    print(result_dict)
    for i in result_dict:
        del i['_sa_instance_state']
        dic = list(i.keys())
        for di in dic:
            i[di] = str(i[di])

    return jsonify(result_dict)
```

**Comment by paw787878** [comment]
Czemu gdzieś masz abort 405 zamiast abort ( 400 ) jak w poleceniu?
Mi zaczęło działać gdy dodałem jakiegoś try except i wysłałem odpowiedni kod błedu gdy doszło do excepta. Bo problem jest chyba jak są dwa zapytania na raz. To znaczy jak sobie w tym postmanie dwa razy klikniesz send to prawdopodobnie będzie jakiś bład.

**Comment by ularom234** [comment]
ok a w którym miejscu powinna uwzględnić ten try i except? przy zapisywaniu nowego artysty? czy też mam w nim uwzględnić wyświetlanie jsona?

**Comment by paw787878** [comment]
W sumie to spróbuj wszystko dać w try except, bo w sumie to nic nie może zepsuć. Tylko pamiętaj by except wysyłał dobry kod w aborcie.

**Comment by jfpio** [comment]
Na pewno jest błąd w tym co zwracasz, bo zwracasz listę jsonów, a nie jsona. wystarczy, że zmienisz
return jsonify(result_dict)
na:
return jsonify(result_dict[0])

**Comment by cv16r5** [comment]
Po pierwsze jak wspomniał jfpio musisz zwrócić dict a nie listę. Po drugie testy mogą Ci nie przechodzić poniewać kod nie jest odporny na dwa różne argumenty. Jężeli wysyłasz  jsona np. { "name": "abc",    "name1": "abc"} to kod zwróci 200 ponieważ znalazł w słowniku "name".

**Comment by ularom234** [comment]
juz sie udalo dzieki :)
