### ISSUE TITLE
Zadanko 2

### ISSUE THREAD

**Issue by Piotr296** [daftcode/daftacademy-python_levelup-spring2019#4]
from flask import Flask
from flask import request

app2 = Flask(__name__)

@app2.route("/methods", methods=['GET'])
def method_return_get():
    return request.method

@app2.route("/methods", methods=['POST'])
def method_return_post():
    return request.method

@app2.route("/methods", methods=['PUT'])
def method_return_put():
    return request.method

if __name__ == '__main__':
    app2.run(debug=True)

Aplikacja jest zdeployowana na heroku, Na localhoście(curl) prawidłowo zwraca mi nazwę metody. Czemu testy na Replu nie chcą przejść?

**Comment by gignacy** [comment]
methods daj w jednej liście, a nie trzy dekoratory i funkcje:
 @app.route('/method', methods=['GET', 'POST', 'PUT', 'DELETE'])


czyli: 


```
from flask import Flask, request

app = Flask(__name__)

@app.route('/method', methods=['GET', 'POST', 'PUT', 'DELETE'])
def request_info():
    return f'{request.method}'

if __name__ == '__main__':
    app.run(debug=True)

```


Mam nadzieję, że pomogłem.
Pozdrawiam,
Ignacy

**Comment by Piotr296** [comment]
Alles klar! Dzięki!
