### ISSUE TITLE
Zadanie 3 i 4

### ISSUE THREAD

**Issue by gignacy** [daftcode/daftacademy-python_levelup-spring2019#5]
Ja za to mam pytanie do zadań 3 i 4:

```
@app.route('/show_data', methods=['POST'])
def showdata():
    data = request.args
    data = json.dumps(data, ensure_ascii=False)
    return str(data)

@app.route('/pretty_print_name', methods=['POST'])
def printname():
    name = request.args.get('name')
    surname = request.args.get('surname')
    return f'Na imię mu {name}, a nazwisko jego {surname}'
```

Oba testy mi nie przechodzą, ktoś wie gdzie popełniam błędy? Jak wysyłam POSTy ze swojego postmana (do apki postawionej już na heroku) to wszystko jest OK.
Dzięki

**Comment by Piotr296** [comment]
W trzecim poszedłeś nieco na około. Jest dużo prostszy sposób:

@app3.route('/show_data', methods=['POST'])
def show_data_simple_case():
    return jsonify(request.json)

Zaś w czwartym też wyskakuje mi błąd:

@app4.route('/pretty_print_name', methods=['POST'])
def pretty_print_name():
    data = request.get_json()
    name = data['name']
    surename = data['surename']
    return f'Na imię mu {name}, a nazwisko jego {surename}'

**Comment by FHoffmannCode** [comment]
przekleiłem Twoje rozwiązanie do swojej aplikacji i mi testy przechodzą, na moje oko kod też jest spoko.

pokaż jaki błąd Ci replit wypluwa.

**Comment by FHoffmannCode** [comment]
Przeklejam skrin z dokumentacji obiektu Request we flasku: 
![image](https://user-images.githubusercontent.com/13187173/54519530-0ec8a380-4967-11e9-89c1-a871043a7bc1.png)

http://flask.pocoo.org/docs/1.0/api/#flask.Request

Testy Ci nie przechodzą bo `request.args` jest `None`. żeby się dobrać do danych przekazywanych metodą `POST` w formacie json trzeba użyć `request.json` lub metody `request.get_json()`

Nie wiem czemu koledze Piotrowi też wyskakuje błąd, bo jego kod przekleiłem do swojej aplikacji i mi testy przechodzą. Pokaż co Ci wypluwa replit, może będę w stanie pomóc.

**Comment by gignacy** [comment]
Piotrek, pewnie dlatego że zamiast surname dałeś 'pewne imię' :D (surename)

literówka :)

A ja dziękuję za pomoc :)

**Comment by FHoffmannCode** [comment]
hmm akurat ta literówka nie powinna mieć znaczenia, bo w testach i w treści zadania niestety też jest ten językowy kwas :/

**Comment by Piotr296** [comment]
Nie dodałem kodowania. Jak dodałem wszystko zaczęło chodzić

**Comment by FHoffmannCode** [comment]
To trochę dziwne, o ile nie wymusiłeś na heroku jakiejś starszej wersji pythona (a zakładam, że tego nie zrobiłeś, bo używasz składni `f'{cośtam}'`, która jest stosunkowo nowym ficzerem) to kodowanie powinno być z automatu ogarnięte. Pokażesz jak teraz wygląda Twój kod (najlepiej w całości)?

**Comment by Piotr296** [comment]
#-*- coding: utf-8 -*-
from flask import Flask, request
import sys

app4 = Flask(__name__)

@app4.route('/pretty_print_name', methods=['POST'])
def pretty_print():
    data = request.get_json()
    name = data['name']
    surename = data['surename']
    return 'Na imię mu {}, a nazwisko jego {}'.format(name, surename)


if __name__ == '__main__':
    app4.run(debug=True)

Tak wygląda to co przeszło testy. Almost the same z tym, że działa 💃

**Comment by FHoffmannCode** [comment]
to wygląda tak jakbyś z jakiegoś powodu nie miał na heroku pythona 3.6 tylko 2.7. dodawałeś może do swojej apki plik `runtime.txt`?

**Comment by haladamateusz** [comment]
Ja również miałem problem z 4, przyczyną okazała się literówka - surname zamiast surename.
```
@app.route('/pretty_print_name',methods=["POST"])
def pretty_print():
    data = request.get_json()
    imie = data['name']
    nazwisko = data['surename']
    return f"Na imię mu {imie}, a nazwisko jego {nazwisko}"
    
```
Pamiętajcie, że f-stringi działają działają od pythona 3.6 (co możemy przeczytać [w tym PEPIE](https://www.python.org/dev/peps/pep-0498/))
Jeżeli chcecie wymusić na heroku używanie najnowszej wersji pythona (co zostało zaproponowane powyżej) W głównym folderze tworzycie plik ```runtime.txt``` i wpisujecie w nim ```python-3.7.2``` (przynajmniej tak wygląda ta kwestia na windowsie).
