### ISSUE TITLE
zad 3

### ISSUE THREAD

**Issue by jasandra** [daftcode/daftacademy-python_levelup-spring2019#7]
@app.route('/show_data', methods=['POST'])
def show_data():
    return jsonify(request.json)

**Comment by FHoffmannCode** [comment]
Wrzuć cały kod całej Twojej aplikacji proszę. Jesteś pewna, że wykonałaś komendę `git push heroku master` po napisaniu kodu? 

Sprawdzałem Twój endpoint ręcznie i wygląda na to, że niezależnie od tego jakiego jsona mu wyślę, zawsze zwracany jest json `"{\"a\": 10, \"b\": \"text\"}"` więc coś musi być nie tak po stronie aplikacji.

**Comment by jasandra** [comment]
```
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/show_data', methods=['POST'])
def show_data():
    return jsonify(request.json)

if __name__ == '__main__':
    app.run()
```
`git push heroku master` na pewno wykonałam. Wrzuciłam jeszcze raz na heroku https://daft-levelup-1-1.herokuapp.com

**Comment by FHoffmannCode** [comment]
Pod linkiem, który teraz wysłałaś nic nie ma, wyrzuca error 405.

Skopiowałem ten kod, zdeployowałem na swoim heroku i wszystko działa tak jak powinno. 

Zrób tak. Stwórz sobie nowy folder, przejdź do niego w konsoli i wykonaj komendę `heroku git:clone -a APP-NAME` za `APP-NAME` podstawiając nazwę swojej apki. Potem skopiuj CAŁY kod z pliku `app.py` i wklej tutaj. 

Podejrzewam, że z jakiegoś powodu nie masz na heroku tego samego co lokalnie na komputerze.

**Comment by jasandra** [comment]
W `app.py` mam
```
from flask import Flask, request, jsonify

app = Flask(__name__)


@app.route('/show_data', methods=['POST'])
def show_data():
    return jsonify(request.json)


if __name__ == '__main__':
    app.run()
```

**Comment by FHoffmannCode** [comment]
kod z app.py z tego nowego folderu który sobie sklonowałaś za pomocą `heroku git:clone` :P, sorry zapomniałem dopisać.

**Comment by jasandra** [comment]
Po sklonowaniu widzę, że na heroku trafił nie ten plik, z błędnym rozwiązaniem tego zadania ;)
```
@app.route('/show_data', methods=['POST'])
def show_data():
    data = {'a': 10, 'b': 'text'}
    return jsonify(json.dumps(data))
```
sorry za zamieszanie ;)
